# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: vs-ingress-web-api
# spec:
#   hosts:
#     - "*"
#   gateways:
#     - gateway-ingress-http
#     - istio-egressgateway
#   http:
#     - match:
#         - uri:
#             prefix: /products
#       rewrite:
#         uri: "/"
#       route:
#         - destination:
#             host: products
#             subset: v1
#           weight: 50
#         - destination:
#             host: products
#             subset: v2
#           weight: 50
#     - match:
#         - uri:
#             prefix: /httpbin
#           gateways:
#             - istio-egressgateway
#           port: 80
#       rewrite:
#         uri: "/"
#       route:
#         - destination:
#             host: httpbin-se
# ---