apiVersion: v1
kind: Service
metadata:
  name: products-page-service
  labels:
    app: products-page
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      name: http
  selector:
    app: products-page